# Generated by Django 5.1.2 on 2024-11-07 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataleakage', '0002_dataleakfinding_is_user_blocked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataleakfinding',
            name='category',
            field=models.CharField(blank=True, choices=[('personal', 'Personal Information'), ('financial', 'Financial Data'), ('confidential', 'Confidential Documents')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dataleakfinding',
            name='sensitivity_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataleakage.dataleakfinding')),
            ],
        ),
    ]
