# Generated by Django 5.1.2 on 2024-11-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataleakage', '0003_dataleakfinding_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dismissed', models.BooleanField(default=False)),
            ],
        ),
    ]
