# Generated by Django 5.1.2 on 2024-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExplorer', '0004_datafile_findings'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavisualization',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='datavisualization',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('scatter', 'Scatter Plot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datavisualization',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
