# Generated by Django 5.1.2 on 2024-11-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_useractivitylog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_blocked',
        ),
    ]
