# Generated by Django 5.1.2 on 2024-11-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_remove_profile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
