# Generated by Django 5.1.2 on 2024-10-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_task_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
